remote: true
remote-name: origin
git-name: Go Semver Release
git-email: 39492740+s0ders@users.noreply.github.com
tag-prefix: v
branches:
  - name: main
rules:
  minor:
    - feat
  patch:
    - fix
    - perf
    - revert
