version: 1

env:
  - CGO_ENABLED=0

goos: windows
goarch: amd64

main: ./main.go

binary: go-semver-release-{{ .Os }}-{{ .Arch }}.exe

ldflags:
  - "-X github.com/s0ders/go-semver-release/v8/cmd.cmdVersion={{ .Env.VERSION }}"
  - "-X github.com/s0ders/go-semver-release/v8/cmd.buildNumber={{ .Env.BUILD_NUMBER }}"
  - "-X github.com/s0ders/go-semver-release/v8/cmd.buildCommitHash={{ .Env.COMMIT_HASH }}"
  - "-w"
  - "-s"